SHELL := /bin/sh

# disable suffix rules
SUFFIXES:
# disable implicit rule
%.o: %.c

OBJDIR := .objs-readmcr
DEPDIR := .deps-readmcr

.DEFAULT_GOAL := all
.PHONY: all clean

all: readmcr

clean:
	rm -rf readmcr $(DEPDIR) $(OBJDIR) readmcr.dSYM

CFLAGS = -std=gnu99 -Wall -Wextra -I. -O3 -ggdb3
DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.d

$(OBJDIR): ; mkdir -p $@
$(DEPDIR): ; mkdir -p $@

# implicit rule to compile objects
$(OBJDIR)/%.o: %.c $(DEPDIR)/%.d | $(OBJDIR) $(DEPDIR)
	$(CC) $(CFLAGS) $(DEPFLAGS) -c -o $@ $<

SRCS := readmcr.c udiss.c misc.c usym.c
OBJS := $(SRCS:%.c=$(OBJDIR)/%.o)
DEPS := $(SRCS:%.c=$(DEPDIR)/%.d) 

readmcr: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

# dependency files has no dependency
$(DEPS):

include $(wildcard $(DEPS))
