#pragma once

/*
 * See SYS;COLD:QCOM LISP for the canonical definition.
 */

static struct {
	char *name;
	uint32_t a;
	uint32_t v;
} area_list[] = {
	{"A-V-RESIDENT-SYMBOL-AREA", 0, 0},
	{"A-V-SYSTEM-COMMUNICATION-AREA", 0, 0},
	{"A-V-SCRATCH-PAD-INIT-AREA", 0, 0},
	{"A-V-MICRO-CODE-SYMBOL-AREA", 0, 0},
	{"A-V-REGION-ORIGIN", 0, 0},
	{"A-V-REGION-LENGTH", 0, 0},
	{"A-V-REGION-BITS", 0, 0},
	{"A-V-REGION-FREE-POINTER", 0, 0},
	{"A-V-PAGE-TABLE-AREA", 0, 0},
	{"A-V-PHYSICAL-PAGE-DATA", 0, 0},
	{"A-V-ADDRESS-SPACE-MAP", 0, 0},
	{"A-V-REGION-GC-POINTER", 0, 0},
	{"A-V-REGION-LIST-THREAD", 0, 0},
	{"A-V-AREA-NAME", 0, 0},
	{"A-V-AREA-REGION-LIST", 0, 0},
	{"A-V-AREA-REGION-BITS", 0, 0},
	{"A-V-AREA-REGION-SIZE", 0, 0},
	{"A-V-AREA-MAXIMUM-SIZE", 0, 0},
	{"A-V-SUPPORT-ENTRY-VECTOR", 0, 0},
	{"A-V-CONSTANTS-AREA", 0, 0},
	{"A-V-EXTRA-PDL-AREA", 0, 0},
	{"A-V-MICRO-CODE-ENTRY-AREA", 0, 0},
	{"A-V-MICRO-CODE-ENTRY-NAME-AREA", 0, 0},
	{"A-V-MICRO-CODE-ENTRY-ARGS-INFO-AREA", 0, 0},
	{"A-V-MICRO-CODE-ENTRY-MAX-PDL-USAGE", 0, 0},
	{"A-V-MICRO-CODE-PAGING-AREA", 0, 0},
	{"A-V-PAGE-GC-BITS", 0, 0},
	{"A-V-PAGE-STRUCTURE-HANDLES", 0, 0},
	{"A-V-MICRO-CODE-ENTRY-ARGLIST-AREA", 0, 0},
	{"A-V-MICRO-CODE-SYMBOL-NAME-AREA", 0, 0},
	{"A-V-LINEAR-PDL-AREA", 0, 0},
	{"A-V-LINEAR-BIND-PDL-AREA", 0, 0},
	{"A-V-INIT-LIST-AREA", 0, 0},
	{(char *)0, 0, 0}
};

static struct {
	char *name;
	uint32_t a;
	uint32_t v;
} system_communication_area_qs[] = {
	{"%SYS-COM-AREA-ORIGIN-PNTR", 0, 0},
	{"%SYS-COM-VALID-SIZE", 0, 0},
	{"%SYS-COM-PAGE-TABLE-PNTR", 0, 0},
	{"%SYS-COM-PAGE-TABLE-SIZE", 0, 0},
	{"%SYS-COM-OBARRAY-PNTR", 0, 0},
	{"%SYS-COM-ETHER-FREE-LIST", 0, 0},
	{"%SYS-COM-ETHER-TRANSMIT-LIST", 0, 0},
	{"%SYS-COM-ETHER-RECEIVE-LIST", 0, 0},
	{"%SYS-COM-BAND-FORMAT", 0, 0},
	{"%SYS-COM-GC-GENERATION-NUMBER", 0, 0},
	{"%SYS-COM-UNIBUS-INTERRUPT-LIST", 0, 0},
	{"%SYS-COM-TEMPORARY", 0, 0},
	{"%SYS-COM-FREE-AREA#-LIST", 0, 0},
	{"%SYS-COM-FREE-REGION#-LIST", 0, 0},
	{"%SYS-COM-MEMORY-SIZE", 0, 0},
	{"%SYS-COM-WIRED-SIZE", 0, 0},
	{"%SYS-COM-CHAOS-FREE-LIST", 0, 0},
	{"%SYS-COM-CHAOS-TRANSMIT-LIST", 0, 0},
	{"%SYS-COM-CHAOS-RECEIVE-LIST", 0, 0},
	{"%SYS-COM-DEBUGGER-REQUESTS", 0, 0},
	{"%SYS-COM-DEBUGGER-KEEP-ALIVE", 0, 0},
	{"%SYS-COM-DEBUGGER-DATA-1", 0, 0},
	{"%SYS-COM-DEBUGGER-DATA-2", 0, 0},
	{"%SYS-COM-MAJOR-VERSION", 0, 0},
	{"%SYS-COM-DESIRED-MICROCODE-VERSION", 0, 0},
	{"%SYS-COM-HIGHEST-VIRTUAL-ADDRESS", 0, 0},
	{"%SYS-COM-POINTER-WIDTH", 0, 0},
	{(char *)0, 0, 0}
};

enum Q_FIELD_VALUES {
	Q_CDR_CODE_ = 03602,
	Q_BOXED_SIGN_BIT_ = 03001,
	Q_DATA_TYPE_ = 03105,
	Q_POINTER_ = 00031,
	Q_POINTER_WITHIN_PAGE_ = 00010,
	Q_TYPED_POINTER_ = 00036,
	Q_ALL_BUT_TYPED_POINTER_ = 03602,
	Q_ALL_BUT_POINTER_ = 03107,
	Q_ALL_BUT_CDR_CODE_ = 00036,
	Q_HIGH_HALF_ = 02020,
	Q_LOW_HALF_ = 00020,
	CH_FONT_ = 01010,
	CH_CHAR_ = 00010,
	KBD_CHAR_ = 00010,
	KBD_CONTROL_META_ = 02504,
	KBD_CONTROL_ = 02501,
	KBD_META_ = 02601,
	KBD_SUPER_ = 02701,
	KBD_HYPER_ = 03001,
	KBD_MOUSE_ = 02401,
	KBD_MOUSE_BUTTON_ = 00003,
	KBD_MOUSE_N_CLICKS_ = 00303,
	BYTE_SPECIFIER_POSITION_ = 00627,
	BYTE_SPECIFIER_SIZE_ = 00006
};

enum Q_DATA_TYPES {
	DTP_TRAP = 0,
	DTP_NULL = 1,
	DTP_FREE = 2,
	DTP_SYMBOL = 3,
	DTP_SYMBOL_HEADER = 4,
	DTP_FIX = 5,
	DTP_EXTENDED_NUMBER = 6,
	DTP_HEADER = 7,
	DTP_GC_FORWARD = 8,
	DTP_EXTERNAL_VALUE_CELL_POINTER = 9,
	DTP_ONE_Q_FORWARD = 10,
	DTP_HEADER_FORWARD = 11,
	DTP_BODY_FORWARD = 12,
	DTP_LOCATIVE = 13,
	DTP_LIST = 14,
	DTP_U_ENTRY = 15,
	DTP_FEF_POINTER = 16,
	DTP_ARRAY_POINTER = 17,
	DTP_ARRAY_HEADER = 18,
	DTP_STACK_GROUP = 19,
	DTP_CLOSURE = 20,
	DTP_SMALL_FLONUM = 21,
	DTP_SELECT_METHOD = 22,
	DTP_INSTANCE = 23,
	DTP_INSTANCE_HEADER = 24,
	DTP_ENTITY = 25,
	DTP_STACK_CLOSURE = 26,
	DTP_SELF_REF_POINTER = 27,
	DTP_CHARACTER = 28
};

enum FEFH_CONSTANT_VALUES {
	FEFH_PC = 077777,
	FEFH_NO_ADL = 1 << 18,
	FEFH_FAST_ARG = 1 << 17,
	FEFH_SV_BIND = 1 << 16,
	FEFH_PC_ = 00017,
	FEFH_PC_IN_WORDS_ = 00116,
	FEFH_NO_ADL_ = 02201,
	FEFH_GET_SELF_MAPPING_TABLE_ = 01701,
	FEFH_FAST_ARG_ = 02101,
	FEFH_SV_BIND_ = 02001
};

enum FEFHI_INDEXES {
	FEFHI_IPC = 0,
	FEFHI_STORAGE_LENGTH = 1,
	FEFHI_FCTN_NAME = 2,
	FEFHI_FAST_ARG_OPT = 3,
	FEFHI_SV_BITMAP = 4,
	FEFHI_MISC = 5,
	FEFHI_SPECIAL_VALUE_CELL_PNTRS = 6
};

enum FEFHI_VALUES {
	FEFHI_FSO_MIN_ARGS_ = 00606,
	FEFHI_FSO_MAX_ARGS_ = 00006,
	FEFHI_MS_LOCAL_BLOCK_LENGTH_ = 00007,
	FEFHI_MS_ARG_DESC_ORG_ = 00710,
	FEFHI_MS_BIND_DESC_LENGTH_ = 01710,
	FEFHI_MS_DEBUG_INFO_PRESENT_ = 02701,
	FEFHI_SVM_ACTIVE_ = 02601,
	FEFHI_SVM_ACTIVE = 1 << 26,
	FEFHI_SVM_BITS_ = 00026,
	FEFHI_SVM_HIGH_BIT_ = 02501
};

enum NUMERIC_ARG_DESC_INFO {
	ARG_DESC_QUOTED_REST = 010000000,
	ARG_DESC_QUOTED_REST_ = 02501,
	ARG_DESC_EVALED_REST = 04000000,
	ARG_DESC_EVALED_REST_ = 02401,
	ARG_DESC_ANY_REST_ = 02402,
	ARG_DESC_FEF_QUOTE_HAIR = 02000000,
	ARG_DESC_FEF_QUOTE_HAIR_ = 02301,
	ARG_DESC_INTERPRETED = 01000000,
	ARG_DESC_INTERPRETED_ = 02201,
	ARG_DESC_FEF_BIND_HAIR = 0400000,
	ARG_DESC_FEF_BIND_HAIR_ = 02101,
	ARG_DESC_MIN_ARGS_ = 00606,
	ARG_DESC_MAX_ARGS_ = 00006
};
