all:
	$(MAKE) -C libhosts all
	$(MAKE) -C cmd all
	$(MAKE) -C chsocket all

clean:
	$(MAKE) -C libhosts clean
	$(MAKE) -C cmd clean
	$(MAKE) -C chsocket clean

check:
	$(MAKE) -C libhosts check
	$(MAKE) -C cmd all
	$(MAKE) -C chsocket all
